package com.claims.dto.request;

import com.claims.enums.ReportScope;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AnalyticsReportRequest {

    @NotNull(message = "Scope is required")
    private ReportScope scope;

    @NotBlank(message = "Scope value is required")
    private String scopeValue;

    @NotBlank(message = "Metrics is required")
    private String metrics;

    @NotNull(message = "Generated date is required")
    private LocalDate generatedDate;

    @NotBlank(message = "Generated by is required")
    private String generatedBy;

    // Optional — report data snapshot as JSON string
    private String reportData;
}
