package com.claims.service;

import com.claims.dto.response.AnalyticsReportResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;

/** Renders an AnalyticsReportResponse as PDF (OpenPDF) or CSV (RFC 4180). */
@Service
@RequiredArgsConstructor
@Slf4j
public class ReportExportService {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    // ── PDF ──────────────────────────────────────────────────────────────────

    public byte[] toPdf(AnalyticsReportResponse report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, out);
            doc.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, new Color(0x22, 0x22, 0x22));
            Font subFont   = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(0x66, 0x66, 0x66));
            Font h2Font    = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, new Color(0x55, 0x55, 0x55));
            Font cellFont  = FontFactory.getFont(FontFactory.HELVETICA, 10, new Color(0x22, 0x22, 0x22));
            Font cellKey   = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, new Color(0x44, 0x44, 0x44));
            Font footFont  = FontFactory.getFont(FontFactory.HELVETICA, 8, new Color(0x99, 0x99, 0x99));

            Paragraph title = new Paragraph(
                    "Report #" + report.getReportId() + " \u2014 " + safe(report.getScope() == null ? "" : report.getScope().name()),
                    titleFont);
            doc.add(title);
            doc.add(new Paragraph("ClaimInsight analytics report", subFont));
            doc.add(new Paragraph(" "));

            // Meta table
            PdfPTable meta = new PdfPTable(2);
            meta.setWidthPercentage(100);
            meta.setWidths(new float[]{1f, 3f});
            addRow(meta, "Scope",          report.getScope() == null ? "" : report.getScope().name(), cellKey, cellFont);
            addRow(meta, "Scope value",    safe(report.getScopeValue()),    cellKey, cellFont);
            addRow(meta, "Metrics",        safe(report.getMetrics()),       cellKey, cellFont);
            addRow(meta, "Generated by",   safe(report.getGeneratedBy()),   cellKey, cellFont);
            addRow(meta, "Generated date", report.getGeneratedDate() == null ? "" : report.getGeneratedDate().toString(),
                    cellKey, cellFont);
            doc.add(meta);

            doc.add(new Paragraph(" "));
            doc.add(new Paragraph("Report data", h2Font));
            doc.add(new Paragraph(" "));

            // Payload table
            Map<String, String> rows = flattenPayload(report.getReportData());
            PdfPTable body = new PdfPTable(2);
            body.setWidthPercentage(100);
            body.setWidths(new float[]{1f, 2f});
            // header row
            body.addCell(headerCell("Field", cellKey));
            body.addCell(headerCell("Value", cellKey));
            if (rows.isEmpty()) {
                PdfPCell empty = new PdfPCell(new Phrase("No report payload recorded.", subFont));
                empty.setColspan(2);
                empty.setPadding(10f);
                body.addCell(empty);
            } else {
                rows.forEach((k, v) -> addRow(body, k, v, cellKey, cellFont));
            }
            doc.add(body);

            doc.add(new Paragraph(" "));
            Paragraph footer = new Paragraph(
                    "Generated " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")) +
                            " \u00b7 ClaimInsight360",
                    footFont);
            footer.setAlignment(Element.ALIGN_RIGHT);
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (Exception ex) {
            log.error("Failed to render PDF for report {}: {}", report.getReportId(), ex.getMessage(), ex);
            throw new IllegalStateException("Failed to render PDF", ex);
        }
    }

    private static void addRow(PdfPTable table, String k, String v, Font keyFont, Font valFont) {
        PdfPCell kc = new PdfPCell(new Phrase(k, keyFont));
        PdfPCell vc = new PdfPCell(new Phrase(v == null ? "" : v, valFont));
        kc.setPadding(6f); vc.setPadding(6f);
        kc.setBackgroundColor(new Color(0xF8, 0xF7, 0xF3));
        table.addCell(kc);
        table.addCell(vc);
    }

    private static PdfPCell headerCell(String text, Font font) {
        PdfPCell c = new PdfPCell(new Phrase(text, font));
        c.setBackgroundColor(new Color(0xEF, 0xEE, 0xE8));
        c.setPadding(6f);
        return c;
    }

    // ── CSV ──────────────────────────────────────────────────────────────────

    public String toCsv(AnalyticsReportResponse report) {
        StringBuilder sb = new StringBuilder();
        sb.append("Field,Value\r\n");
        sb.append(csvRow("Report ID",     String.valueOf(report.getReportId())));
        sb.append(csvRow("Scope",         report.getScope() == null ? "" : report.getScope().name()));
        sb.append(csvRow("Scope value",   safe(report.getScopeValue())));
        sb.append(csvRow("Metrics",       safe(report.getMetrics())));
        sb.append(csvRow("Generated by",  safe(report.getGeneratedBy())));
        sb.append(csvRow("Generated date",
                report.getGeneratedDate() == null ? "" : report.getGeneratedDate().toString()));
        Map<String, String> rows = flattenPayload(report.getReportData());
        if (!rows.isEmpty()) {
            sb.append("\r\n");
            rows.forEach((k, v) -> sb.append(csvRow(k, v)));
        }
        return sb.toString();
    }

    private static String csvRow(String k, String v) {
        return csvCell(k) + "," + csvCell(v) + "\r\n";
    }

    private static String csvCell(String s) {
        if (s == null) return "";
        if (s.indexOf(',') >= 0 || s.indexOf('"') >= 0 || s.indexOf('\n') >= 0 || s.indexOf('\r') >= 0) {
            return "\"" + s.replace("\"", "\"\"") + "\"";
        }
        return s;
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /** Parse the report's JSON payload into a flat key→string map. */
    private static Map<String, String> flattenPayload(String json) {
        Map<String, String> out = new LinkedHashMap<>();
        if (json == null || json.isBlank()) return out;
        try {
            JsonNode node = MAPPER.readTree(json);
            if (node.isObject()) {
                Iterator<Map.Entry<String, JsonNode>> fields = node.fields();
                while (fields.hasNext()) {
                    Map.Entry<String, JsonNode> e = fields.next();
                    JsonNode v = e.getValue();
                    out.put(e.getKey(), v.isValueNode() ? v.asText() : v.toString());
                }
                return out;
            }
        } catch (Exception ignore) { /* fall through */ }
        out.put("data", json);
        return out;
    }

    private static String safe(String s) {
        return s == null ? "" : s;
    }
}
