package com.claims.repository;

import com.claims.entity.AnalyticsReport;
import com.claims.enums.ReportScope;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

@Repository
public interface AnalyticsReportRepository extends JpaRepository<AnalyticsReport, Long> {

    // Find all reports by scope type (e.g. all REGION reports)
    List<AnalyticsReport> findByScope(ReportScope scope);

    // Find all reports for a specific scope value (e.g. "North Region")
    List<AnalyticsReport> findByScopeValue(String scopeValue);

    // Find all reports by scope and scope value
    List<AnalyticsReport> findByScopeAndScopeValue(ReportScope scope, String scopeValue);

    // Find all reports generated on a specific date
    List<AnalyticsReport> findByGeneratedDate(LocalDate generatedDate);

    // Find all reports generated within a date range
    List<AnalyticsReport> findByGeneratedDateBetween(LocalDate startDate, LocalDate endDate);

    // Find all reports generated by a specific user
    List<AnalyticsReport> findByGeneratedBy(String generatedBy);

    // Find the most recent report for a given scope and scope value
    @Query("SELECT r FROM AnalyticsReport r WHERE r.scope = :scope AND r.scopeValue = :scopeValue ORDER BY r.generatedDate DESC")
    List<AnalyticsReport> findLatestByScopeAndScopeValue(ReportScope scope, String scopeValue);

    // Count reports grouped by scope type
    @Query("SELECT r.scope, COUNT(r) FROM AnalyticsReport r GROUP BY r.scope")
    List<Object[]> countByScope();
}
