import { useEffect, useReducer, useCallback } from 'react';
import {
  Table, Button, Modal, Form, Input, Select, DatePicker,
  Typography, Space, Tag, Alert, Tooltip, Popconfirm, Card, Row, Col, Statistic,
} from 'antd';
import { PlusOutlined, ReloadOutlined, DeleteOutlined, BarChartOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import { reportsApi, AnalyticsReport, CreateReportRequest, REPORT_SCOPES } from '../../api/reportsApi';

const { Title, Text } = Typography;
const { Option } = Select;
const { TextArea } = Input;

// ── Reducer ───────────────────────────────────────────────────────────────────

interface State {
  items: AnalyticsReport[];
  loading: boolean;
  error: string | null;
  modalOpen: boolean;
  submitting: boolean;
  filterScope: string | null;
}

type Action =
  | { type: 'FETCH_START' }
  | { type: 'FETCH_SUCCESS'; payload: AnalyticsReport[] }
  | { type: 'FETCH_ERROR'; payload: string }
  | { type: 'OPEN_MODAL' }
  | { type: 'CLOSE_MODAL' }
  | { type: 'SUBMIT_START' }
  | { type: 'SUBMIT_SUCCESS'; payload: AnalyticsReport }
  | { type: 'SUBMIT_ERROR' }
  | { type: 'DELETE_SUCCESS'; payload: number }
  | { type: 'SET_FILTER'; payload: string | null };

function reducer(state: State, action: Action): State {
  switch (action.type) {
    case 'FETCH_START':    return { ...state, loading: true, error: null };
    case 'FETCH_SUCCESS':  return { ...state, loading: false, items: action.payload };
    case 'FETCH_ERROR':    return { ...state, loading: false, error: action.payload };
    case 'OPEN_MODAL':     return { ...state, modalOpen: true };
    case 'CLOSE_MODAL':    return { ...state, modalOpen: false, submitting: false };
    case 'SUBMIT_START':   return { ...state, submitting: true };
    case 'SUBMIT_SUCCESS': return { ...state, submitting: false, modalOpen: false, items: [action.payload, ...state.items] };
    case 'SUBMIT_ERROR':   return { ...state, submitting: false };
    case 'DELETE_SUCCESS': return { ...state, items: state.items.filter(i => i.reportId !== action.payload) };
    case 'SET_FILTER':     return { ...state, filterScope: action.payload };
    default:               return state;
  }
}

// ── Component ─────────────────────────────────────────────────────────────────

const SCOPE_COLORS: Record<string, string> = {
  PRODUCT: 'blue', REGION: 'green', CLAIM_TYPE: 'purple', PERIOD: 'orange',
};

export default function ReportsPage() {
  const [state, dispatch] = useReducer(reducer, {
    items: [], loading: false, error: null, modalOpen: false, submitting: false, filterScope: null,
  });
  const [form] = Form.useForm();

  const load = useCallback(async () => {
    dispatch({ type: 'FETCH_START' });
    try {
      const data = state.filterScope
        ? await reportsApi.getByScope(state.filterScope)
        : await reportsApi.getAll();
      dispatch({ type: 'FETCH_SUCCESS', payload: data });
    } catch {
      dispatch({ type: 'FETCH_ERROR', payload: 'Failed to load reports' });
    }
  }, [state.filterScope]);

  useEffect(() => { load(); }, [load]);

  const handleCreate = async (values: Record<string, unknown>) => {
    dispatch({ type: 'SUBMIT_START' });
    try {
      const req: CreateReportRequest = {
        scope:         values.scope as string,
        scopeValue:    values.scopeValue as string,
        metrics:       values.metrics as string,
        generatedDate: (values.generatedDate as dayjs.Dayjs).format('YYYY-MM-DD'),
        generatedBy:   values.generatedBy as string,
        reportData:    values.reportData as string | undefined,
      };
      const record = await reportsApi.create(req);
      dispatch({ type: 'SUBMIT_SUCCESS', payload: record });
      form.resetFields();
    } catch {
      dispatch({ type: 'SUBMIT_ERROR' });
    }
  };

  const handleDelete = async (id: number) => {
    await reportsApi.delete(id);
    dispatch({ type: 'DELETE_SUCCESS', payload: id });
  };

  const scopeCounts = REPORT_SCOPES.reduce((acc, s) => ({
    ...acc, [s]: state.items.filter(i => i.scope === s).length,
  }), {} as Record<string, number>);

  const columns: ColumnsType<AnalyticsReport> = [
    { title: 'ID',           dataIndex: 'reportId',     key: 'reportId',     width: 80 },
    {
      title: 'Scope',        dataIndex: 'scope',        key: 'scope',
      render: v => <Tag color={SCOPE_COLORS[v] ?? 'default'}>{v}</Tag>,
      filters: REPORT_SCOPES.map(s => ({ text: s, value: s })),
      onFilter: (value, rec) => rec.scope === value,
    },
    { title: 'Scope Value',  dataIndex: 'scopeValue',   key: 'scopeValue' },
    { title: 'Metrics',      dataIndex: 'metrics',      key: 'metrics',      ellipsis: true },
    { title: 'Generated By', dataIndex: 'generatedBy',  key: 'generatedBy',  render: v => <Text code>{v}</Text> },
    { title: 'Generated Date', dataIndex: 'generatedDate', key: 'generatedDate', sorter: (a, b) => a.generatedDate.localeCompare(b.generatedDate) },
    {
      title: 'Report Data',  dataIndex: 'reportData',   key: 'reportData',
      render: v => v ? <Tag color="green">Available</Tag> : <Tag color="default">None</Tag>,
    },
    {
      title: 'Action', key: 'action', width: 80,
      render: (_, rec) => (
        <Popconfirm title="Delete this report?" onConfirm={() => handleDelete(rec.reportId)}>
          <Tooltip title="Delete"><Button icon={<DeleteOutlined />} size="small" danger /></Tooltip>
        </Popconfirm>
      ),
    },
  ];

  return (
    <div>
      <div style={styles.header}>
        <div>
          <Title level={3} style={{ margin: 0 }}>Analytics Reports</Title>
          <Text type="secondary">Generated analytics and performance reports</Text>
        </div>
        <Space>
          <Select
            allowClear
            placeholder="Filter by scope"
            style={{ width: 160 }}
            value={state.filterScope}
            onChange={v => dispatch({ type: 'SET_FILTER', payload: v ?? null })}
          >
            {REPORT_SCOPES.map(s => <Option key={s} value={s}>{s}</Option>)}
          </Select>
          <Button icon={<ReloadOutlined />} onClick={load}>Refresh</Button>
          <Button type="primary" icon={<PlusOutlined />} onClick={() => dispatch({ type: 'OPEN_MODAL' })}>
            Generate Report
          </Button>
        </Space>
      </div>

      <Row gutter={16} style={{ marginBottom: 24 }}>
        <Col xs={12} sm={6}>
          <Card style={styles.statCard}>
            <Statistic title="Total Reports" value={state.items.length}
              prefix={<BarChartOutlined />} valueStyle={{ color: '#2563eb' }} />
          </Card>
        </Col>
        {REPORT_SCOPES.map(s => (
          <Col xs={12} sm={4} key={s} style={{ flex: 1 }}>
            <Card style={styles.statCard}>
              <Statistic title={s} value={scopeCounts[s] ?? 0}
                valueStyle={{ color: SCOPE_COLORS[s] === 'blue' ? '#2563eb' : undefined, fontSize: 18 }} />
            </Card>
          </Col>
        ))}
      </Row>

      {state.error && <Alert type="error" message={state.error} style={{ marginBottom: 16 }} />}

      <Table
        rowKey="reportId"
        columns={columns}
        dataSource={state.items}
        loading={state.loading}
        pagination={{ pageSize: 10 }}
        bordered size="middle"
      />

      <Modal
        title="Generate Analytics Report"
        open={state.modalOpen}
        onCancel={() => { dispatch({ type: 'CLOSE_MODAL' }); form.resetFields(); }}
        onOk={() => form.submit()}
        confirmLoading={state.submitting}
        destroyOnClose
      >
        <Form form={form} layout="vertical" onFinish={handleCreate}>
          <Form.Item name="scope" label="Scope" rules={[{ required: true }]}>
            <Select placeholder="Select scope">
              {REPORT_SCOPES.map(s => <Option key={s} value={s}><Tag color={SCOPE_COLORS[s]}>{s}</Tag></Option>)}
            </Select>
          </Form.Item>
          <Form.Item name="scopeValue" label="Scope Value" rules={[{ required: true }]}>
            <Input placeholder="e.g. AUTO, NORTH_EAST, Q1-2026" />
          </Form.Item>
          <Form.Item name="metrics" label="Metrics" rules={[{ required: true }]}>
            <Input placeholder="e.g. TAT, LOSS_RATIO, CYCLE_TIME" />
          </Form.Item>
          <Form.Item name="generatedBy" label="Generated By" rules={[{ required: true }]}>
            <Input placeholder="username" />
          </Form.Item>
          <Form.Item name="generatedDate" label="Generated Date" rules={[{ required: true }]}>
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item name="reportData" label="Report Data (optional)">
            <TextArea rows={4} placeholder='{"summary": "..."}' />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  header:   { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24, flexWrap: 'wrap', gap: 12 },
  statCard: { borderRadius: 10, border: '1px solid #e2e8f0' },
};
